---

- name: Create user
  user: 
    name: "{{ lookup('env', 'USER') }}"
    state: present
    shell: /bin/bash

- name: Add ssh key to user
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Add user as sudoer
  lineinfile:
    create: yes
    state: present
    dest: /etc/sudoers.d/ansible_sudoer
    line: "{{ lookup('env', 'USER') }} ALL=(ALL) NOPASSWD: ALL"

- name: Upgrade packages to latest versions
  apt:
    upgrade: dist
    update_cache: yes

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Install common packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - vim
    - screen
